# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'send_sms.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from send_pattern import send_sms_pattern

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 541, 131))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(150, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.number_label = QtWidgets.QLabel(self.centralwidget)
        self.number_label.setGeometry(QtCore.QRect(130, 150, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.number_label.setFont(font)
        self.number_label.setObjectName("number_label")
        self.price_label = QtWidgets.QLabel(self.centralwidget)
        self.price_label.setGeometry(QtCore.QRect(150, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.price_label.setFont(font)
        self.price_label.setObjectName("price_label")
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(210, 120, 113, 20))
        self.name_edit.setObjectName("name_edit")
        self.number_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.number_edit.setGeometry(QtCore.QRect(210, 160, 113, 20))
        self.number_edit.setObjectName("number_edit")
        self.price_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.price_edit.setGeometry(QtCore.QRect(210, 200, 113, 20))
        self.price_edit.setObjectName("price_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 568, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_copy = QtWidgets.QAction(MainWindow)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtWidgets.QAction(MainWindow)
        self.action_paste.setObjectName("action_paste")
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.menuFile.addAction(self.action_new)
        self.menuFile.addAction(self.action_save)
        self.menuEdit.addAction(self.action_copy)
        self.menuEdit.addAction(self.action_paste)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.pushButton.clicked.connect(self.clicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Send a normal sms to some number!"))
        self.pushButton.setText(_translate("MainWindow", "Send!"))
        self.name_label.setText(_translate("MainWindow", "name"))
        self.number_label.setText(_translate("MainWindow", "number"))
        self.price_label.setText(_translate("MainWindow", "price"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.action_copy.setText(_translate("MainWindow", "copy"))
        self.action_copy.setStatusTip(_translate("MainWindow", "Copy a file"))
        self.action_copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_paste.setText(_translate("MainWindow", "paste"))
        self.action_paste.setStatusTip(_translate("MainWindow", "paste a file"))
        self.action_paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.action_new.setText(_translate("MainWindow", "new"))
        self.action_new.setStatusTip(_translate("MainWindow", "create new file"))
        self.action_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_save.setText(_translate("MainWindow", "save"))
        self.action_save.setStatusTip(_translate("MainWindow", "save an existed file"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))

    def clicked(self):
        gui_name = self.name_edit.text()
        gui_number = self.number_edit.text()
        # pid: pattern id, tnum: receiver, p1-p*: keys, v1-v*: values
        send_sms_pattern(pid='gca4bd0ilvjrr8c', tnum=gui_number, p1='name', v1=gui_name)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
